### ISSUE TITLE
TransactionResponse.getAmountsProcessed() should be @NonNull

### ISSUE THREAD

**Issue by louis-barman** [AEVI-AppFlow/pos-android-sdk#165]
Other methods that return an Amount (e.g. `getRequestedAmounts`, `getProcessedAmounts()`, `getRemainingAmounts`) are marked as @NonNull  and so `TransactionResponse.getAmountsProcessed` should marked as  `@NonNull` as well.

**Comment by andreas-borglin** [comment]
Yes, but unlike the other models, we don't create the `TransactionResponse`. The payment app does. We can not force them to set amounts, for when it's declined for instance

**Comment by louis-barman** [comment]
In the `TransactionResponse` constructor  method it could have the following code
```
 this.amounts = amounts != null ? amounts : new Amount(0,"XXX")
```
Marking the currency as "XXX" as not so good though for zero amounts. so for this 
issue can be closed.
