### ISSUE TITLE
Add method `PaymentResponse.getRemainingAmounts`

### ISSUE THREAD

**Issue by louis-barman** [AEVI-AppFlow/pos-android-sdk#166]
For partial payments it would be clearer if a method `getRemainingAmounts` was added to the `PaymentResponse` API. Also the java docs for  `Transaction.getRemainingAmounts()  need updating to explain that is not always the remaining amount the needs to be paid on the originating payment.

**Comment by andreas-borglin** [comment]
I'm not sure what you mean by "Also the java docs for `Transaction.getRemainingAmounts() need updating to explain that is not always the remaining amount the needs to be paid on the originating payment." ?

**Comment by louis-barman** [comment]
The java docs for `Transaction.getRemainingAmounts()  state "This *shall* be used to determine how much to charge the customer at any given point." 

Perhaps a better wording be "This is the amount remaining unpaid after this transaction has completed, Please see  `PaymentResponse.getRemainingAmounts` for the amount still due on the original  payment initiation request "
