### ISSUE TITLE
PaymentServiceSample

### ISSUE THREAD

**Issue by shambhu-sharan** [AEVI-AppFlow/pos-android-sdk#173]
Warning: Default Activity not found

unable to install this on device

**Comment by brettwold** [comment]
Hi @shambhu-sharan , I assume you are trying to install this sample application via Android Studio? In which case the message is correct. This application deliberately has no default Activity. It is designed to only be called during the execution of a flow from our Flow Processing Service (FPS).

To install via Android Studio you simply need to edit the Run/Debug configuration from the dropdown at the top. Select "Edit Configurations" then under "Launch Options" change the "Launch" dropdown to "Nothing". This will allow you to install directly from Android Studio but remember it will only be called during the execution of flow (payment) from FPS.
